name: weather_test
description: A simple weather app in Flutter

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
  

